[package]
name = "ceresdb-client-py"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = { version = "0.16", features = ["extension-module", "abi3-py37"] }
pyo3-asyncio = { version = "0.16", features = ["attributes", "tokio-runtime"] }
tokio = { version = "1", features = ["sync"] }

[dependencies.ceresdb-client-rs]
git = "https://github.com/CeresDB/ceresdb-client-rs.git"
rev = "7259d141a92f82049f6c58c3c1bd9f69e3fc61fe"

[dependencies.common_types]
git = "https://github.com/CeresDB/ceresdb.git"
rev = "f6c9a5b03e23b04e6a06c4f73756f1be9551c0f8"

[lib]
crate-type = ["cdylib"]
name = "ceresdb_client_py"
