[project]
name = "ceresdb-client-py"
version = "0.1.0"
description = "The python client for ceresdb."
readme = "README.md"
requires-python = ">=3.6"
license = { file = "LICENSE" }
authors = [
    { name = "CeresDB Authors", email = "<ceresdbservice@gmail.com>" }
]
keywords = ["CeresDB"]

[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"
